# The URL the site will be built for
base_url = "https://hugoarnal.com"

compile_sass = false
build_search_index = false

# https://www.getzola.org/documentation/templates/feeds/
generate_feeds = true

[markdown]
github_alerts = true

[markdown.highlighting]
dark_theme = "one-dark-pro"
light_theme = "catppuccin-latte"
